### ISSUE TITLE
Error #2030: End of file was encountered.

### ISSUE THREAD

**Issue by mrfrasier** [DigitalStrawberry/ANE-Bugsnag#7]
I've been trying to trace the source of this message for a while. I finally found that if I comment out the Bugsnag.init() call in my code it goes away. Any idea what in this ANE could be causing this?

**Comment by timoisalive** [comment]
I've seen this also, but I thought it was my Google Analytics ANE tracing the error! :)

I believe Bugsnag writes data into the device for it's internal use, and sometimes the data cannot be read. That's at least what I thought it would be in GA ANE case.

It would be nice if ANE's in general offered a way to silence the traces, and when not silenced, would let the developer clearly know who's tracing, and all the relevant information related to the trace (error in this case).

**Comment by ecornbower** [comment]
This is actually coming from the Actionscript side of the ANE. Events are queued while waiting to be submitted to the server in case the user does not have an internet connection. I believe this error is due to the initial data store not being properly written out to disk.

This shouldn't be causing any issues, however I'll have one of our developers dig further into this and see if we can figure out what is causing the problem in the first place.

**Comment by marpies** [comment]
This issue is now fixed. As Kevin said, it was due to the file being incorrectly written out to storage, causing an error when being loaded.

Note you may see this or similar error pop up the first time your app is launched after updating the ANE because the ANE will try to load the corrupted file (if there is one on the device). Once a request is made to the Bugsnag servers, the file will be overwritten (correctly now) and it should not appear again.

**Comment by timoisalive** [comment]
Thanks guys, no more #2030! :)
